#!/bin/bash -e

# TODO: Replace with https://sh.rustup.rs when it supports -y and such
rustup_init_url='https://raw.githubusercontent.com/rust-lang-nursery/rustup.rs/master/rustup-init.sh'

function for-target {
    local wanted_target
    wanted_target=$1
    shift

    if [[ "$TARGET" == "$wanted_target" ]]
    then "$@"
    fi
}

function install-musl {
    curl 'http://www.musl-libc.org/releases/musl-1.1.15.tar.gz' | tar xzf -
    cd musl-1.1.15
    mkdir "$HOME/musl"
    ./configure --prefix="$HOME/musl"
    make -sj
    make -sj install
}

function ci-install {
    for-target x86_64-unknown-linux-musl install-musl

    curl "$rustup_init_url" -sSf | sh -s -- -y --default-toolchain="$TOOLCHAIN"

    if ! rustup target list | grep -F '(default)' | grep -Fq "$TARGET"
    then rustup target add "$TARGET"
    fi
}

function ci-test {
    serde_protobuf/gen-test
    cargo test --manifest-path serde_protobuf/Cargo.toml --target "$TARGET"
    cargo test --target="$TARGET"
}

function ci-coverage {
    wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz
    tar xzf master.tar.gz
    cd kcov-master
    mkdir build
    cd build
    cmake ..
    make
    sudo make install
    cd ../..
    rm -rf kcov-master

    for file in target/$TARGET/debug/rq-* target/$TARGET/debug/record_query-* target/$TARGET/debug/lib-*
    do
        kcov --exclude-pattern=/.cargo,/usr/lib --verify "target/cov" "$file"
    done

    bash <(curl -s https://codecov.io/bash)
    echo "Uploaded code coverage"
}

function ci-deploy {
    cargo build --release --target="$TARGET"
    mkdir -p "target/deploy/$TARGET"
    cp "target/$TARGET/release/rq" "target/deploy/$TARGET/rq"
    mkdir -p "target/deploy-release"
    cp "target/$TARGET/release/rq" "target/deploy-release/rq-$TARGET"
}

function ci-deploy-gh-pages {
    curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
    sudo apt-get install -y nodejs
    sudo npm install -g jsdoc
    cargo doc
    jsdoc -c jsdoc/conf.json -d target/doc/js src/api.js src/prelude.js

    cd target/doc
    git init
    git config user.email 'nobody@nobody.org'
    git config user.name 'Travis CI'
    git add .
    git commit -m "Generate rustdoc for $TRAVIS_COMMIT"
    git push --force "https://${GITHUB_TOKEN}@github.com/dflemstr/rq.git" master:gh-pages
}

case "$1" in
    install )
        shift; ci-install "$@" ;;
    test )
        shift; ci-test "$@" ;;
    coverage )
        shift; for-target x86_64-unknown-linux-gnu ci-coverage "$@" ;;
    deploy )
        shift; ci-deploy "$@" ;;
    deploy-gh-pages )
        shift; for-target x86_64-unknown-linux-gnu ci-deploy-gh-pages "$@" ;;
esac
