#!/bin/bash -e

rustup_init_url='https://static.rust-lang.org/rustup.sh'

function for-target {
    local wanted_target
    wanted_target=$1
    shift

    if [[ "$TARGET" == "$wanted_target" ]]
    then "$@"
    fi
}

function retry {
    local times
    local n

    times="$1"
    shift
    n=0

    until [ "$n" -ge "$times" ]
    do
        "$@" && break
        n=$(($n + 1))
    done
}

function run-docker {
    docker pull "dflemstr/buildenv:$TARGET"
    mkdir -p "$HOME/.cargo"
    exec docker run \
         --privileged \
         --rm -ti \
         --entrypoint /bin/bash \
         -u root \
         -v "$HOME/.cargo:$HOME/.cargo" \
         -v "$PWD:/host" \
         -e "HOME=$HOME" \
         -e "TARGET=$TARGET" \
         -e "GITHUB_TOKEN=$GITHUB_TOKEN" \
         -e "SKIP_TESTS=$SKIP_TESTS" \
         -e "USE_DOCKER=false" \
         -e "IN_DOCKER=true" \
         "dflemstr/buildenv:$TARGET" \
         -c "if ! getent group $(id -gn)
             then groupadd -g $(id -g) $(id -gn)
             fi &&
             if ! getent passwd $(id -un)
             then useradd -u $(id -u) -g $(id -g) -m $(id -un)
             fi &&
             chown $(id -un):$(id -gn) -R $HOME &&
             adduser $(id -un) sudo &&
             cd /host &&
             sudo -HEu $(id -un) ./ci $*"

}

function apt-install {
    sudo apt-get update
    export DEBIAN_FRONTEND=noninteractive
    sudo apt-get install -y --no-install-recommends "$@"
    sudo rm -rf /var/lib/apt/lists/*
}

function install-rust {
    if ! which cargo &>/dev/null
    then
        curl "$rustup_init_url" -sSLfo rust-installer.sh
        retry 3 sh rust-installer.sh -y --spec=stable --with-target="$TARGET"
    fi
}

function install-v8 {
    if [ ! -d v8-build ]
    then
        wget "https://s3-eu-west-1.amazonaws.com/record-query/v8/$TARGET/5.6.222/v8-build.tar.gz"
        tar -xvf v8-build.tar.gz
    fi

    export V8_LIBS=$PWD/v8-build/lib/libv8uber.a
    export V8_SOURCE=$PWD/v8-build
}

function install-deps {
    apt-install clang libclang-dev qemu-user-static binfmt-support
}

function ci-test {
    local extra_args
    if [ "${SKIP_TESTS:-false}" = true ]
    then extra_args=(--target "$TARGET" --no-run)
    else extra_args=(--target "$TARGET")
    fi

    install-rust
    install-v8
    install-deps

    cargo test "${extra_args[@]}"
}

function ci-deploy {
    install-rust
    install-v8
    install-deps

    cargo build --release --target="$TARGET"
    mkdir -p "target/deploy/$TARGET"
    strip "target/$TARGET/release/rq"
    cp "target/$TARGET/release/rq" "target/deploy/$TARGET/rq"
    mkdir -p "target/deploy-release"
    cp "target/$TARGET/release/rq" "target/deploy-release/rq-$TARGET"
}

function ci-deploy-gh-pages {
    curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
    apt-install nodejs
    sudo npm install -g jsdoc
    jsdoc -c jsdoc/conf.json -d target/doc/js src/api.js src/prelude.js

    cd target/doc
    git init
    git config user.email 'nobody@nobody.org'
    git config user.name 'Travis CI'
    git add .
    git commit -m "Generate rustdoc for $TRAVIS_COMMIT"
    git push --force "https://${GITHUB_TOKEN}@github.com/dflemstr/rq.git" master:gh-pages
}

function print-gcc-search-args {
    "$@" -print-search-dirs | grep libraries | cut -d= -f2 | tr : '\n' | xargs readlink -f | xargs -I'{}' echo '"-L", "native={}",'
}

if [ "${USE_DOCKER:-false}" = true ] && [ "${IN_DOCKER:-false}" = false ]
then run-docker "$@"
fi

export CROSS_COMPILE="$TARGET-"
mkdir -p .cargo
echo -e "[target.$TARGET]\nlinker = \"$TARGET-g++\"" > .cargo/config

target_search_args=$(print-gcc-search-args "$TARGET-g++")
host_search_args=$(print-gcc-search-args "g++")

if [[ "$TARGET" == *musl* ]]
then
  echo -e "rustflags = [
    $target_search_args
    \"-C\", \"link-args=-static-libstdc++ -static-libgcc\"
  ]" >> .cargo/config
else
  echo -e "rustflags = [${target_search_args%,}]" >> .cargo/config
fi

echo -e "[build]\nrustflags = [${host_search_args%,}]" >> .cargo/config

case "$1" in
    test )
        shift; ci-test "$@" ;;
    deploy )
        shift; ci-deploy "$@" ;;
    deploy-gh-pages )
        shift; for-target x86_64-unknown-linux-gnu ci-deploy-gh-pages "$@" ;;
esac
